#ifndef __PACKMLMODULE_ENUMS_HPP__
#define __PACKMLMODULE_ENUMS_HPP__



enum PackMLModuleStateEnu {
	ST_UNDEFINED = 0,
	ST_CLEARING = 1,
	ST_STOPPED = 2,
	ST_STARTING = 3,
	ST_IDLE = 4,
	ST_SUSPENDED = 5,
	ST_EXECUTE = 6,
	ST_STOPPING = 7,
	ST_ABORTING = 8,
	ST_ABORTED = 9,
	ST_HOLDING = 10,
	ST_HELD = 11,
	ST_UNHOLDING = 12,
	ST_SUSPENDING = 13,
	ST_UNSUSPENDING = 14,
	ST_RESETTING = 15,
	ST_COMPLETING = 16,
	ST_COMPLETE = 17,
	ST_DEACTIVATING = 30,
	ST_DEACTIVATED = 31,
	ST_ACTIVATING = 32
};




	
enum PackMLModuleEnu {
	NO_ERROR = 0,
	WARNING_INVALID_CMD = 1,
	INFO_PARENT_NOT_ACTIVE = 2,
	ERROR_BLAH = 3,
};



#endif